### ISSUE TITLE
Please update apidoc dependency to 0.14

### ISSUE THREAD

**Issue by alqu** [ayhankuru/gulp-apidoc#10]
Since they changed the behaviour how GET-Parameters are generated (finally!), it looks like a good change.

Thank you in advance.

**Comment by ayhankuru** [comment]
notice that, now new version published.

**Comment by ayhankuru** [comment]
0.2.1 published

**Comment by alqu** [comment]
Thanks!

**Comment by ayhankuru** [comment]
@alqu sorry install 0.2.2

**Comment by alqu** [comment]
Ah, OK, done.
