### ISSUE TITLE
Any way of being able to inject a `<base href="">`?

### ISSUE THREAD

**Issue by u01jmg3** [ayhankuru/gulp-apidoc#6]
I'm looking to load the contents of the generated documentation elsewhere and would like to be able to set a `<base href="">` so I can do this. Would this be something that could be added? Or is there a way to do this already?

Thanks

**Comment by ayhankuru** [comment]
Download this template, https://github.com/apidoc/apidoc/tree/master/template change the code and,
template directory use
```js
gulp.task('apidoc',function(){
              apidoc.exec({
                  src: "example/",
                  dest: "build/",
                  template: "template/",
                  debug: true,
                  includeFilters: [ ".*\\.js$" ]
              });
});
```

**Comment by u01jmg3** [comment]
Thanks - fixed my issue
