### ISSUE TITLE
Error if no apidoc comment found

### ISSUE THREAD

**Issue by gpaton** [ayhankuru/gulp-apidoc#7]
Hello,

If you don't have any apidoc docblocks in your code, gulp-apidoc plugin has an issue : 

    info: Nothing to do.  
    [11:37:34] 'apidoc' errored after 376 ms  
    [11:37:34] Error in plugin 'gulp-apidoc'  
    Message:  
        Execution terminated (set " debug: true " in gulpfile.js for details.

**Comment by ayhankuru** [comment]
@gpaton share to gulpfile

**Comment by gpaton** [comment]
My `gulpfile.js`? it won't be of any help :
```javascript
'use strict';
require('./gulp');
```

My `apidoc` task `apidoc.js` :

```javascript
'use strict';

var gulp   = require('gulp');
var apidoc = require('gulp-apidoc');

gulp.task('apidoc', function() {
    apidoc.exec({
        src: './src',
        dest: './apidoc',
        includeFilters: [ ".*\\.php$" ]
    });
});
```

**Comment by ayhankuru** [comment]
``` debug:true ``` as you try? and output share me?

**Comment by gpaton** [comment]
Nothing changed when I put debug: true

**Comment by ayhankuru** [comment]
I think there are src folder broken, and debug will be output. share git url  I'm test out :/

**Comment by gpaton** [comment]
I've created the followingrepository with a demonstration of the issue if you want to test it out :

https://github.com/gpaton/demo-gulp-apidoc

**Comment by ayhankuru** [comment]
@gpaton Thanks, I found the problem, I'm now working the patch version :+1:

**Comment by ayhankuru** [comment]
@gpaton  thanks for this issue, must be resolved.

But your problem, nothing php file apidoc comment :) 

[Checkout example](http://apidocjs.com/#example-basic)

**Comment by gpaton** [comment]
Thank you, issue resolved.

However, I have this message even if there's no apidoc generated, strange behaviour no ?
`gulp-apidoc Apidoc created...`

**Comment by ayhankuru** [comment]
@gpaton php file apidoc comment need :)

**Comment by gpaton** [comment]
:wink:
